### ISSUE TITLE
a bug in code when using HC module

### ISSUE THREAD

**Issue by f414158949** [jcwang123/FedLC#4]
Sincere thanks for sharing the training codes!

when I set args.hc = 1, there is an error:

Traceback (most recent call last):  File "scripts/train_lcfed.py", line 223, in <module>
    pred, x5, hmap = net_current(volume_batch, client_idx, 1, seg_heads)
  File "/home/anaconda3/envs/torch11/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/FedLC-main/scripts/../networks/lcrepnet.py", line 243, in forward
    o = self.forward_for_train(x, site_index, stage, seg_heads)  
  File "/home/FedLC-main/scripts/../networks/lcrepnet.py", line 236, in forward_for_train
    o = self.hc(uncertainty.detach(), preds.detach(), fea.detach())
  File "/home/anaconda3/envs/torch11/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)  
  File "/home/FedLC-main/scripts/../networks/lcrepnet.py", line 30, in forward
    fea2 = self.soft(uncertainty[:, c].unsqueeze(1), fea) + fea
  File "/home/anaconda3/envs/torch11/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by jcwang123** [comment]
Please try to run the new script, "train_multi_lcfed.py"

**Comment by jcwang123** [comment]
sorry for the bugs. I was trying to make the resources clearer after the eccv submission and modified many functions.
But I'm so busy these days and thus, this repo seems confusing and some bugs occurred. 
I will fix the bugs and update the repo as soon as possible.

**Comment by jcwang123** [comment]
sorry for so long time delay. please see train_hc.py.

**Comment by yuvrajmakkena** [comment]
train_hc.py is missing. 
Please guide on how to start training.
